### PR TITLE
Fix test failures in test_thermalctld.py by passing arguments to ThermalControlDaemon()

### PR DESCRIPTION
**Pull request by louis-nexthop**
#### Description

Fix test failures in test_thermalctld.py, that was introduced in #652. `ThermalControlDaemon.__init__()` now requires 3 arguments, so we have to pass them.

#### Motivation and Context

Fixes https://github.com/sonic-net/sonic-platform-daemons/issues/699, which will allow Azure Pipelines to pass.

`test_get_chassis_exception` and `test_get_chassis_success` were failing with the following error:
```
TypeError: ThermalControlDaemon.__init__() missing 3 required positional arguments: 'thermal_monitor_initial_interval', 'thermal_monitor_update_interval', and 'thermal_monitor_update_elapsed_threshold' 
```

because they didn't pass thermal-monitor-related args to `ThermalControlDaemon()`, which were introduced in https://github.com/sonic-net/sonic-platform-daemons/pull/635.

#### How Has This Been Tested?

Ran unit tests locally and passed.

### CODE REVIEW

**Review by vvolam — APPROVED** [review]
why the https://github.com/sonic-net/sonic-platform-daemons/pull/635 got merged with these test failures, was the code not compiled before raising the PR?
